### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by monjurulkarim** [saccharomycetes/text-based-traffic-understanding#1]
How to get BDD-QA and HDT-QA Dataset?

**Comment by saccharomycetes** [comment]
Hi Muhammad, the two data are under the /data folder of our repo, `bdd.jsonl` and `hdt.jsonl`

**Comment by monjurulkarim** [comment]
@saccharomycetes Thanks for your response. I found the annotation. Could you please direct me to where I can download the corresponding videos?

**Comment by saccharomycetes** [comment]
You are welcome, [here](https://github.com/JinkyuKimUCB/BDD-X-dataset) is the source of the BDD-QA dataset (BDD-X). But to my knowledge, their release of videos is lost. Since our research focuses on textual data only, we did not use the videos of BDD-X.
HDT-QA crawled from [here](https://www.dmv-test-pro.com/), they are text-based traffic-related questions so there is no corresponding video.
For our TV-QA dataset, you can download the corresponding videos [here](https://github.com/SUTDCV/SUTD-TrafficQA), what we did is we provided detailed textual annotations (captions) for each video (a subset of videos in traffic QA) and checked the quality of every question and caption manually and carefully. So I think TV-QA is a good testbed if you want to explore topics about video-QA, causality, etc.

**Comment by monjurulkarim** [comment]
@saccharomycetes Thanks for your detailed response. I agree that TV-QA appears to be an excellent match for our needs. I reached out to [here](https://github.com/SUTDCV/SUTD-TrafficQA) last week to request access to the dataset but haven't received a response yet. Hopefully, they will provide a download link soon.

**Comment by saccharomycetes** [comment]
Of course, I think if you submit your information [here](https://sutdcv.github.io/SUTD-TrafficQA/#/download), you can immediately get the link to the data through Google Drive.

**Comment by monjurulkarim** [comment]
@saccharomycetes Excellent! Many thanks!
